name:                fp2-game-of-life
version:             0.1.0.0
github:              "githubuser/fp2-game-of-life"
license:             BSD-3-Clause
author:              "Aleksey Kazakov"
maintainer:          "axtra2@gmail.com"
copyright:           "2025 Aleksey Kazakov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fp2-game-of-life#readme>

dependencies:
- base >= 4.7 && < 5
- Yampa
- sdl2
- linear
- text
- array
- lens

default-extensions:
- Arrows
- RecordWildCards

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  fp2-game-of-life-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp2-game-of-life

tests:
  fp2-game-of-life-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fp2-game-of-life
